---
AWSTemplateFormatVersion: '2010-09-09'
Description: Api gateway usage plan test stack
Parameters:
  Prefix:
    Type: String
    Description: Prefix for temp stack
    Default: 'et'
  Stage:
    Type: String
    Description: Stack stage
    Default: 'dev'

Resources:

# API Key

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ApiGatewayStage
    Properties:
      Name:
        Fn::Join:
          - '-'
          - - Ref: Prefix
            - Ref: AWS::StackName
      Enabled: "true"
      StageKeys:
        - RestApiId:
            Ref: ApiGateway
          StageName:
            Ref: ApiGatewayStage

# Rest API

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name:
        Fn::Join:
          - '-'
          - - Ref: Prefix
            - Ref: AWS::StackName
            - Ref: Stage

# /hello

  ApiGatewayHelloResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
        - ApiGateway
        - RootResourceId
      PathPart: "hello"
      RestApiId:
        Ref: ApiGateway

# /hello/ method

  ApiGatewayHelloMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: true
      HttpMethod: GET
      ResourceId:
        Ref: ApiGatewayHelloResource
      RestApiId:
        Ref: ApiGateway
      AuthorizationType: NONE
      Integration:
        RequestParameters:
          integration.request.header.Content-Type: "'application/json'"
        RequestTemplates:
          application/json: "{\"statusCode\": 200}"
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: "{\"status\": \"OK\"}"
      MethodResponses:
        - StatusCode: 200

# Deployment

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayHelloMethod
    Properties:
      RestApiId:
        Ref: ApiGateway
      Description: "Initial Deployment"

# Stage

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: ApiGatewayDeployment
      RestApiId:
        Ref: ApiGateway
      ClientCertificateId:
        Ref: ApiGatewayClientCertificate
      StageName:
        Ref: Stage

# Usage Plan

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: ApiGateway
        Stage:
          Ref: ApiGatewayStage
      UsagePlanName:
        Fn::Join:
          - '-'
          - - Ref: Prefix
            - Ref: AWS::StackName
            - Ref: Stage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: ApiKey
      KeyType: API_KEY
      UsagePlanId:
        Ref: UsagePlan

# Client Certificate
  ApiGatewayClientCertificate:
    Type: AWS::ApiGateway::ClientCertificate
    Properties:
      Description:
        Fn::Join:
          - '-'
          - - Ref: Prefix
            - Ref: AWS::StackName
            - "client certificate"
